maxSpeed : 0.5
minSpeed : -0.25
maxYaw_rate : 80 #[degree/s]
maxAccel : 0.5
maxYawVel_rate : 120 #[degree/ss]
v_resolution : 0.01
w_resolution : 0.5 #[degree/s]
dt : 0.1
predictTime : 3
angleCost_gain : 0.2
distanceCost_gain : 0.2
obstacleCost_gain : 0.05
robot_stuck_value : 0.001

map_frame_id : map
base_link_frame_id : base_link
loop_rate : 20