my_costmap:
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_footprint
  footprint: [[-0.3, 0], [-0.21, 0.21], [0, 0.3], [0.21, 0.21], [0.3, 0], [0.21, -0.21], [0, -0.3], [-0.21, -0.21]]
  update_frequency: 2.0
  publish_frequency: 2.0
  static_layer:
    map_topic: "map"
    track_unknown_space: false
    subscribe_to_updates: true
  inflation_layer:
    inflation_radius: 0.45