my_costmap:
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  footprint: [[-0.18, 0], [-0.14, 0.14], [0, 0.18], [0.14, 0.14], [0.18, 0], [0.14, -0.14], [0, -0.18], [-0.14, -0.14]]
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.1
  update_frequency: 20.0
  publish_frequency: 20.0

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: lidar_link
      topic: scan
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range : 20
      raytrace_range : 20
  inflation_layer:
    inflation_radius: 0.6
    cost_scaling_factor : 5

  path_costmap:
    cost_path_width: 0.4