my_costmap:
  plugins: 
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_footprint
  footprint: [[-0.22, 0], [-0.16, 0.16], [0, 0.22], [0.16, 0.16], [0.22, 0], [0.16, -0.16], [0, -0.22], [-0.16, -0.16]]
  rolling_window: true
  width: 4.0
  height: 5.0
  resolution: 0.05
  update_frequency: 20.0
  publish_frequency: 20.0

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: lidar_link
      topic: scan_filtered
      data_type: LaserScan
      marking: true
      clearing: true
  inflation_layer:
    inflation_radius: 0.45
    
