image_width: 1280
image_height: 720
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 925.5943 ,    0.     ,  637.79826,
            0.     ,  925.05306,  387.20566,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.122061, -0.235642, 0.002497, 0.000498, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 930.08276,    0.     ,  638.28856,    0.     ,
            0.     ,  939.43158,  388.51163,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
