obstacle_range: 0.3
raytrace_range: 0.3
footprint: [[0.14, 0.16], [-0.14, 0.16], [-0.14, -0.16], [0.14, -0.16]]
# robot_radius: 0.16
# inflation_radius: 0.19
# cost_scaling_factor: 10.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true}